In [1]:
# Лабораторна робота 1.Байков Олександр

import numpy as np

# 1. Одновимірний масив з перших 20 натуральних чисел
vec_20 = np.arange(1, 21)
print("1. Вектор з перших 20 натуральних чисел:\n", vec_20)

# 2. Двовимірний масив 4x4, заповнений одиницями
matrix_ones = np.ones((4, 4))
print("\n2. Матриця 4x4, заповнена одиницями:\n", matrix_ones)

# 3. Масив 5x5 з випадковими дійсними числами в діапазоні від -1 до 1
matrix_random_5x5 = np.random.uniform(-1, 1, (5, 5))
print("\n3. Матриця 5x5 з випадковими дійсними числами від -1 до 1:\n", matrix_random_5x5)

# 4. Масив 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
matrix_random_3x3 = np.random.rand(3, 3)
print("\n4. Матриця 3x3 з випадковими дійсними числами від 0 до 1:\n", matrix_random_3x3)

# 5. Два одновимірні масиви розміром 6 з випадковими цілими числами від 1 до 20
arr1 = np.random.randint(1, 21, 6)
arr2 = np.random.randint(1, 21, 6)
print("\n5. Два одновимірні масиви:\n", "arr1 =", arr1, "\narr2 =", arr2)
print("Сума:", arr1 + arr2)
print("Різниця:", arr1 - arr2)
print("Добуток:", arr1 * arr2)

# 6. Дві матриці 3x2 і 2x4 з випадковими цілими числами від 1 до 5, перемноження
A = np.random.randint(1, 6, (3, 2))
B = np.random.randint(1, 6, (2, 4))
C = A @ B
print("\n6. Матриця A (3x2):\n", A)
print("Матриця B (2x4):\n", B)
print("Добуток A @ B (3x4):\n", C)

# 7. Матриця 3x3 з випадковими дійсними числами від 0 до 1 та транспонування
M = np.random.rand(3, 3)
print("\n7. Матриця 3x3:\n", M)
print("Транспонована матриця:\n", M.T)

# 8. Дві матриці 3x3 з випадковими цілими числами від 1 до 10, знаходження різниці
A1 = np.random.randint(1, 11, (3, 3))
A2 = np.random.randint(1, 11, (3, 3))
print("\n8. Матриця A1:\n", A1)
print("Матриця A2:\n", A2)
print("Різниця A1 - A2:\n", A1 - A2)

# 9. Дві матриці 3x3 з випадковими цілими числами від -5 до 5, знаходження добутку
B1 = np.random.randint(-5, 6, (3, 3))
B2 = np.random.randint(-5, 6, (3, 3))
print("\n9. Матриця B1:\n", B1)
print("Матриця B2:\n", B2)
print("Добуток B1 @ B2:\n", B1 @ B2)

# 10. Матриця 3x3 з випадковими дійсними числами від -1 до 1 та вектор-стовпчик сум рядків
M_sum = np.random.uniform(-1, 1, (3, 3))
row_sums = np.sum(M_sum, axis=1).reshape(-1, 1)
print("\n10. Матриця M:\n", M_sum)
print("Вектор-стовпчик сум рядків:\n", row_sums)


1. Вектор з перших 20 натуральних чисел:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

2. Матриця 4x4, заповнена одиницями:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3. Матриця 5x5 з випадковими дійсними числами від -1 до 1:
 [[-0.71329566 -0.3321043  -0.4935504  -0.57337221  0.25957911]
 [-0.07995907  0.24190594  0.0324773   0.97936766  0.39959317]
 [-0.73902339  0.1689081  -0.7123121   0.64739505  0.65470652]
 [-0.36769294  0.34568891  0.7609941  -0.63648326 -0.75011084]
 [-0.29335761  0.31643669 -0.09543856  0.5910566   0.05977789]]

4. Матриця 3x3 з випадковими дійсними числами від 0 до 1:
 [[0.58714786 0.29446018 0.05655511]
 [0.30046667 0.22263699 0.68211534]
 [0.32344806 0.31590078 0.10015604]]

5. Два одновимірні масиви:
 arr1 = [20 15 18 10 20 13] 
arr2 = [ 1  3  1 13 13  9]
Сума: [21 18 19 23 33 22]
Різниця: [19 12 17 -3  7  4]
Добуток: [ 20  45  18 130 260 117]

6. Матриця A (3x2):
 [[1 3]
 [3 3]
 [3 4]]
Матриця B (2x4):
 [[5 2 5 3]
 [4